tiffany: Changed to display_headers dependencies
device/xiaomi/tiffany/camera/QCamera2/HAL3/QCamera3Channel.h:37:10: 
fatal error: 'gralloc_priv.h' file not found